test_gelu/test_gelu_develop.py, test_gelu/test_gelu_incubate.py
=> add gelu test

test_gather/test_gather_develop.py, test_gather/test_gather_incubate.py
=> add gather tests

test_embedding/test_embedding_develop.py, test_embedding/test_embedding_incubate.py
embedding api测试结果 ：
incubate 测试：
develop测试：
=> add embedding api test

test_softmax/test_softmax_develop.py, test_softmax/test_softmax_incubate.py
1. develop分支。**给softmax的静态图输入增加uint64支持后，均可通过测试。**
2. incubate分支。**给softmax的静态图输入增加uint64支持后，均可通过测试。**
=> Add softmax tests

test_reshape/test_reshape_develop.py, test_reshape/test_reshape_incubate.py
=> add reshape test

test_cross_entropy/test_cross_entropy_develop.py, test_cross_entropy/test_cross_entropy_incubate.py
Add cross_entropy op test
fp32: pass
bfp16: 
2.4   not register kernel
develop   after open bfp16 restrict in api, diff is large.
=> Add cross_entropy op test

test_split/test_split_develop.py, test_split/test_split_incubate.py
=> add split test

test_mean/test_mean_develop.py, test_mean/test_mean_incubate.py
1. mean算子不支持bf16数据类型，屏蔽掉后测试可全部通过
=> Add mean test

test_fc/test_fc_develop.py, test_fc/test_fc_incubate.py
fluid.layers.fc VS paddle.incubate.nn.functional.fused_linear
=> add fc test

test_linear/test_linear_develop.py
yifei update test_linear_develop, weight -0.5 ~0.5
=> yifei update test_linear_develop, weight -0.5 ~0.5

test_parallel_cross_entropy/prepare_data.py
补充测试结论：
多次测试后develop分支fp32数据类型2卡、8卡同样出现不稳定问题，但是小概率触发，4卡不稳定问题大概率触发
其余测试结果与之前相同
=> Modify Test Data Range of fleet.meta_parallel.ParallelCrossEntropy

test_dist_split/prepare_data.py
=> Modify Test Data Range of paddle.distributed.split

test_gelu/test_gelu_develop.py
=> Show Extreme Cases of gelu

test_mp_allreduce/README.md, test_mp_allreduce/get_and_test_paddle_result.py, test_mp_allreduce/get_torch_result.py, test_mp_allreduce/prepare_data.py, test_mp_allreduce/test_mp_allreduce.sh
=> Change Assert Log For paddle.distributed.collective._mp_allreduce

test_gather/test_gather_develop.py, test_reshape/test_reshape_develop.py, test_split/test_split_develop.py
=> add log for paddle.gather, paddle.reshape_, paddle.split tests

test_parallel_cross_entropy/get_and_test_paddle_result.py, test_parallel_cross_entropy/prepare_data.py
fleet.meta_parallel.ParallelCrossEntropy test修改，小shape已跑通
=> add log for fleet.meta_parallel.ParallelCrossEntropy test

test_linear/test_linear_develop.py
add log for test develop linear
=> add log for test develop linear

test_square/test_square_develop.py
add `paddle.square` test in develop branch.
=> add square develop test

test_cos/test_cos_develop.py
The test results have been updated in docment
=> Add cos test

test_equal/test_equal_develop.py
The test results have been updated
=> Add equal test

test_divide/test_divide_develop.py
=> fix divide test

test_add/test_add_develop.py, test_add_inplace/test_add_inplace_develop.py
add_不支持静态图
add x和y shape不同的一个case反向出diff
=> add test of paddle.add and add_

test_slice/test_slice_develop.py, test_slice/test_stride_slice_develop.py
add slice and stride_slice test
=> add slice and stride slice test

test_stack/test_stack_develop.py
=> Add Stack test

test_split/test_split_develop_v2.py
=> add split retest

test_slice/test_slice_develop.py
=> modify slice test

test_unsqueeze/test_unsqueeze_develop.py
=> add unsqueeze

test_assign/test_assign_develop.py, test_pow/test_pow_develop.py
=> Pow and assign

test_broadcast/README.md, test_broadcast/get_and_test_paddle_result.py, test_broadcast/init_config_class.py, test_broadcast/prepare_data.py, test_broadcast/test_broadcast.sh
=> Add broadcast test

utils.py
=> modify utils

test_fp32_with_bf16/test_layernorm/test_layernorm_fp32vsbfp16.py
=> fix layer_norm bf16vsfp32 test

test_full/test_full_develop.py, test_reshape/test_reshape_develop_new_frl.py, test_reshape_inplace/test_reshape_inplace_develop_new_frl.py, test_slice/test_slice_develop.py, test_split/test_split_develop_v2.py, test_transpose/test_transpose_develop.py, test_unsqueeze/test_unsqueeze_develop.py
Add some unittests of some operators under different shapes including full, reshape, transfer, deserialize, slice, split.
NOTE：In order to be consistent with the test_reshape， test_reshape_inplace is from case 7 to 22.
=> add some unittests

api_test.py, test_square/test_square_develop.py, utils.py
=> support api test framework

test_bmm/bmm_new.log, test_bmm/test_bmm.sh, test_bmm/test_bmm_develop.py, test_clip/clip_new.log, test_clip/test_clip.sh, test_clip/test_clip_develop.py, test_cumprod/cumprod_new.log, test_cumprod/test_cumprod.sh, test_cumprod/test_cumprod_develop.py, test_einsum/einsum_new.log, test_einsum/test_einsum.sh, test_einsum/test_einsum_develop.py, test_exp/exp_new.log, test_exp/test_exp.sh, test_exp/test_exp_develop.py, test_expand/expand_new.log, test_expand/test_expand.sh, test_expand/test_expand_develop.py, test_flatten/flatten_new.log, test_flatten/test_flatten.sh, test_flatten/test_flatten_develop.py
add test for the following ops: bmm, clip, cumprod, einsum, exp, expand, flatten
=> Add 7 tests for ops

mse_loss/test_mse_loss.py, test_conv_nd/test_conv_nd_develop.py, test_flash_attention/test_flash_attention_develop2.py, test_gaussian/test_gaussian_develop.py, test_group_norm/test_group_norm_develop.py, test_randint/test_randint_develop.py, test_stack/test_stack_develop.py, test_uniform/test_uniform_develop.py, test_zero_/test_zero__develop.py, utils.py
Add uts for `mse_loss`, `conv_nd`, `flash_attention`, `gaussian`, `group_norm`, `randint`, `stack`, `uniform`, `zero_`
=> Add some api uts
